name: Pack and Publish Package
run-name: Pack and Publish ${{ github.event_name == 'release' && github.event.release.tag_name || inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version, e.g. `1.0.0` or `1.2.3-pre1`'
        type: string
        required: true
  # Remove this if the workflow of this project is not `Publish release on GitHub → Build and publish package` but something like, for example, `Push tag → Run tests → Build → Publish package and create release on GitHub in parallel`.
  release:
    types: [published]

permissions:
  packages: write
  # Required for NPM trusted publishing. See: https://docs.npmjs.com/trusted-publishers.
  id-token: write

jobs:
  test:
    name: Run Checks
    uses: ./.github/workflows/checks.yml
  pack:
    name: Pack Package
    uses: ./.github/workflows/pack-package.yml
    with:
      version: ${{ github.event_name == 'release' && github.event.release.tag_name || inputs.version }}

  publish:
    name: Publish Package
    needs:
      - test
      - pack
    uses: ./.github/workflows/publish-package.yml
    with:
      ref: ${{ github.event_name == 'release' && github.event.release.tag_name || '' }} # This is needed when the release tag is created by GitHub on publish. In this case, checkout may use the commit hash instead of the tag, which breaks npm provenance. We work around this by explicitly specifying the tag ref here.
      version: ${{ needs.pack.outputs.version }}
      packed-package-artifact-name: ${{ needs.pack.outputs.packed-package-artifact-name }}
    secrets: inherit
